### ISSUE TITLE
Suggest to use websockets to load feed items

### ISSUE THREAD

**Issue by johnhorsema** [voussoir/bringrss#2]
The captioned suggestion can mitigate the layout thrashing issue. By making it a non-blocking proceses, the browesr may render the UI without waiting for the requests.

You may take a look at [Turbo Steams](https://turbo.hotwired.dev/handbook/streams) for some idea.

**Comment by voussoir** [comment]
Hi,

The layout thrashing occurs after the data has already been received, so the choice of transmitting over AJAX vs SSE vs websockets should not make a difference. I am already using [fragments](https://github.com/voussoir/bringrss/blob/6d40170c782d94b435c1156cbc52e0aaefced722/frontends/bringrss_flask/templates/root.html#L1410) to improve the insertion of each batch of items.

> the browser may render the UI without waiting for the requests

The insertions are batched not because the client is waiting for data over the wire, but because it's better for the user to see some items immediately instead of waiting for all X,000 to render in a single insert. Larger batch sizes make each UI stutter longer, but the overall loading process finishes sooner because the number of reflows is ultimately less. Streaming the items in a larger number of smaller batches leads to more reflows and an overall longer loading time with more stuttering.

**Comment by johnhorsema** [comment]
I see the issue. The thrashing occurs in the DOM when you are rendering the additional items after the first batch is loaded.

The exact issue may be that on loading the 301st item, the scrollbar does not compensate the increased container height for additional items.

You may take advantage of the `scrollHeight`, `clientHeight` and `scrollTop` to solve the thrashing while scrolling down and loading the items (reference: https://stackoverflow.com/a/33238025).

The gist is to initiate the loading before the scroll indicator reaches the end of the page, with at least some buffer for the items to load in view.

**Comment by voussoir** [comment]
The link you provided describes the same sort of thing that I referred to as virtual scrolling on the [readme](https://github.com/voussoir/bringrss/blob/6d40170c782d94b435c1156cbc52e0aaefced722/README.md?plain=1#L135).

I don't want to implement virtual scrolling, but I did a test to see if precomputing the scroll height would improve the layout thrashing:

```Javascript
news_list = document.createElement("div");
news_list.id = "news";
right.appendChild(news_list);

news_scrollbox = document.createElement("div");
news_scrollbox.id = "news_scrollbox";
news_list.appendChild(news_scrollbox);

const news_count = newss.length;
news_scrollbox.style.minHeight = (news_count * 20) + "px";

...

news_scrollbox.appendChild(fragment);
```

In a second test, I also added:

```CSS
.news
{
    height: 20px;
    min-height: 20px;
    max-height: 20px;
}
```

Normally this would be no good since news have variable length titles and the user can shrink their window, but I wanted to see if having a precomputed scrollbox and a fixed height for each item would help the layout engine. It didn't really:

![2022-03-29_11-59-02](https://user-images.githubusercontent.com/7299570/160687706-27752791-8bde-46d3-818a-2f9d8e86d984.png)

**Comment by johnhorsema** [comment]
Oh no, it's not to directly manipulate the element height before appending the items.
The thrashing will still occur since the loading happens after scroller reaches the end of the container box.

It is to add a scroll event listener on the container, and check if the scroller has reached say 80% of the height.
Then load the next batch of items.

```Javascript
let ticking = false;

let updateNewsList = function() {
    var scrolltop= news_list.scrollTop;  
    var scrollheight= news_list.scrollHeight;  
    var windowheight= news_list.clientHeight;

    var scrolloffset = windowheight * 0.2; // 20% of container height

    if(scrolltop>=(scrollheight-(windowheight+scrolloffset))) {
       ...
       news_scrollbox.appendChild(fragment);
    }
}

news_scrollbox.addEventListener('scroll', function(e) {
  if (!ticking) {
    window.requestAnimationFrame(function() {
      updateNewsList();
      ticking = false;
    });

    ticking = true;
  }
});
```

Code reference: https://developer.mozilla.org/en-US/docs/Web/API/Element/scroll_event

**Comment by voussoir** [comment]
I see now that the lazy loading solution is different from virtual scrolling, but it still breaks ctrl+f because the DOM elements don't exist until you scroll to them. In order for the user to ctrl+f they'd have to pagedown to the bottom over and over again until everything is loaded. Or I'd have to add a search box to the page.

Wouldn't the lazy-loading technique still make the UI stutter when the next batch is added to the DOM? With the code that I have now, you can sit back and let it load for a few seconds, then scrolling is smooth. But with lazy loading, you'd get a few hundred milliseconds of stutter every time you page down. And the scroll bar will keep changing size so the user won't really know where the bottom is. This seems ultimately more disruptive. I'd rather race to sleep and have the whole UI rendered as soon as possible.

I just need to help the layout engine make smarter decisions about what needs to be reflowed. That's why I tried the experiment with pre-calculating the height and setting a fixed 20px row height, even though that's not the suggestion you provided.

**Comment by johnhorsema** [comment]
If you take a look at [Panda Reader](https://app.usepanda.com), they've implemented lazy loading for the items list (2nd column). For feeds, they've also got a simple filtering going on.

The lazy loading will 'stutter' if you don't have an offset on when to load the items. By giving it enough offset for scrolling, the list has time to load before the users reaches the bottom.

Also, we may need to clarify two types of loading here: data fetching and UI rendering.

In this app, you may take the approach to load 1000 items all at once, then render them as user scrolls items into the viewport - this is virtual scrolling.

Another approach is to actually lazy load the data fetching, reacting to the user scrolling position with offset. This way there will be the 'stutter' you described, if the offset is not optimized (you need to make sure the time needed to scroll the offset is more or same as the time needed to load the 300 items). Need to do some trial-and-error to get the optimal number, but it's hard, because there are other factors like internet speed or browser compatability...

What I would suggest, is to load the first 1000 items instead of 300, so that the user will take more time to scroll through the buffer and allow more time to load the next 1000 items.

As for the Ctrl-F feature, if you want to balance the infinite loading experience without having to affect this feature, implementing a custom search component is the way to go.

**Comment by voussoir** [comment]
I appreciate your continued interest but I think we are talking past each other. Ultimately, I **don't** want to use javascript to solve this problem, I want to use CSS that helps the layout engine make better reflows.

> The lazy loading will 'stutter' if you don't have an offset on when to load the items. By giving it enough offset for scrolling, the list has time to load before the users reaches the bottom.

> This way there will be the 'stutter' you described, if the offset is not optimized (you need to make sure the time needed to scroll the offset is more or same as the time needed to load the 300 items).

I tried using a scroll eventlistener using your previous code as reference. The insertion of each new fragment causes UI stutter, at least on Chrome, Windows. The UI hangs for about 100-500 ms while the document reflows each new batch. Perhaps your browser's behavior is different and you are able to smoothly scroll the remaining distance while the next batch is prepared, but mine stutters:

https://user-images.githubusercontent.com/7299570/160753600-3b9510f9-f4fd-49aa-b3a1-e7ad30dd7381.mp4

> Also, we may need to clarify two types of loading here: data fetching and UI rendering.

I already clarified this in my first comment. The data is loaded entirely with an AJAX before rendering begins. Since this is first and foremost a localhost program, internet speed is not a real concern. A 1MB+ response containing 10,000+ items is no problem. I do not intend to switch to SSE or websockets or paginated HTTP requests.

> offer "Load next 100" and "Load All" buttons, to hand it over to the users to decide how many to load.

> if you want to balance the infinite loading experience 

I don't want the infinite loading experience! I want to race to sleep. I might consider adding a checkbox so the user can toggle between scroll-based loading vs immediate loading. However this does not improve the performance of each individual fragment insert.
